### PR TITLE
FL-client resource type from deployment to pod

### PR DESCRIPTION
**Pull request by teemuteemu**

### CODE REVIEW

**Review by GerardoGR — CHANGES_REQUESTED** [review]
I think it would help to maintain the Operator having unit-tests for the case when the FLOrchestrator return tasks and the FLOperator starts them. Already testing the bootstrapping case is a good start and we could apply a similar approach.

**Comment by teemuteemu** [comment]
> I think it would help to maintain the Operator having unit-tests for the case when the FLOrchestrator return tasks and the FLOperator starts them. Already testing the bootstrapping case is a good start and we could apply a similar approach.

Related to this, I have some issues running the tests locally using devcontainer and I don't really know what's going on:

```pattern ./...: directory go/pkg/mod/github.com/!azure/go-autorest@v14.2.0+incompatible outside main module or its selected dependencies```

Any ideas?

**Comment by GerardoGR** [comment]
> Related to this, I have some issues running the tests locally using devcontainer and I don't really know what's going on:
> 
> `pattern ./...: directory go/pkg/mod/github.com/!azure/go-autorest@v14.2.0+incompatible outside main module or its selected dependencies`
> 
> Any ideas?

As discussed offline, this was due to running `make test` after `make devcontainer-test`. The `make devcontainer-test` creates a `go/` directory with permissions set to `400` and conflicts with `make test`. The workaround now is `rm -r go/` directory inside the `fl-operator` component.

**Review by nfnt — APPROVED** [review]
LGTM!
Tested manually with a local `kind` cluster. Pods started for clients were cleaned up by the operator once the FL server pipelines was stopped.
RBAC to work with `Pod` resources were missing and have been added in an additional commit.

**Review by GerardoGR — APPROVED** [review]
As agreed offline with @nfnt: Having tested this component manually, we will merge this PR as-is and consider in a following PR a refactoring to improve the testing of the fl-operator.

**Pull request merged**
